CREATE TABLE users ( uID INT NOT NULL AUTO_INCREMENT, username VARCHAR(255) NOT NULL UNIQUE, password VARCHAR(255) NOT NULL, PRIMARY KEY (uID) );
CREATE TABLE authcodes ( codeId INT NOT NULL AUTO_INCREMENT, uID INT NOT NULL, code VARCHAR(255) NOT NULL, expiry INT UNSIGNED NOT NULL, PRIMARY KEY (codeID) );

