CREATE TABLE users ( uID INT NOT NULL AUTO_INCREMENT, uname VARCHAR(255) NOT NULL, pswd VARCHAR(255) NOT NULL, PRIMARY KEY (uID) );
CREATE TABLE authcodes ( codeId INT NOT NULL AUTO_INCREMENT, uID INT NOT NULL, code VARCHAR(255), PRIMARY KEY (codeID) );
